groups:
  groupA:
    - githubName: speculatingwook
      discordKey: BEONGWOOK
    - githubName: paka-jo
      discordKey: JUNGWON
    - githubName: present0917
      discordKey: HYUNJAE

  groupB:
    - githubName: hwan2-99
      discordKey: TAEHWAN
    - githubName: chanwonlee
      discordKey: CHANWON
    - githubName: Bogeun-Kim
      discordKey: BOGEUN
