server:
  port: 8080
  servlet:
    context-path: /api/${api.version}
  name: nolzo
  forward-headers-strategy: framework
  tomcat:
    mbeanregistry:
      enabled: true
    threads:
      max: 400
      min-spare: 20
    max-connections: 10000
    accept-count: 200
    connection-timeout: 20000

api:
  version: v1

spring:
  config:
    import: optional:file:./.env[.properties]
  datasource:
    url: ${MYSQL_DATABASE_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 1200000
  task:
    execution:
      pool:
        core-size: 20
        max-size: 100
        queue-capacity: 200
        keep-alive: 60s
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format_sql: true
        use_sql_comments: true
    open-in-view: false
    show-sql: true

# JWT 설정
jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: ${JWT_ACCESS_TOKEN_VALIDITY_IN_SECONDS}
  refresh-token-validity-in-seconds: ${JWT_REFRESH_TOKEN_VALIDITY_IN_SECONDS}

# CORS 설정
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGIN}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: '*'
  max-age: 3600

# Swagger 설정
swagger:
  server:
    url: ${SWAGGER_SERVER_URL:http://localhost:8080/api/v1}
